- Features/FovChanger.cs
- Features/ToggleFeature.cs
Implementation for #208.
This requires the LateUpdate to override unitys internal animation update. 
This might benefit from a slider instead of a regular float field but works for now.
> added fov changer feature

- Extensions/CameraExtensions.cs
Fixes DLSS by calculating a scale value using Screen.height divided by camera.scaledPixelHeight. Not sure if this is the best method to accomplish this as I am kind of new to C# but local testing shows it works and places all markers in the right spot at all DLSS quality settings. Additionally works with supersampling and downsampling settings.
> Fix DLSS for #230

- Features/LootItems.cs
Added a toggle for showing corpse containers under the loot option. Might not be the best way to accomplish this but it is functional. Occasionally depending on how the body ragdolls the marker can be some distance away from where the container is. Hardcoded name to "Corpse" as the container name is "Default Inventory". Code style is not great as I am still bad at C#. Tested on SPT 3.5.0 and 3.4.1 Fixes #257.
> Added option to display corpse containers

- BepInExPlugin/AkiEftTrainerPlugin.cs
- BepInExPlugin/BepInExPlugin.csproj
- BepInExPlugin/Properties/AssemblyInfo.cs
- EFT.Trainer.sln
- Installer/CompilationContext.cs
- Installer/Compiler.cs
- Installer/ExitCode.cs
- Installer/InstallCommand.cs
- Installer/Installation.cs
- Installer/Installer.csproj
- Installer/UninstallCommand.cs
- Loader.cs
- Properties/AssemblyInfo.cs
Fixes #270 when using SptAki. 
Fixes #41
When used live with EFT `0.13.1.21531`, using the legacy NLog configuration (so not working anymore):
When used with spt-aki `3.4.1`:
```
[Message:   BepInEx] BepInEx 5.4.21.0 - EscapeFromTarkov (1/6/2023 3:32:33 PM)
[Info   :   BepInEx] Running under Unity v0.12.12.2076
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.21.0]
[Info   :   BepInEx] Loaded 1 patcher method from [aki_PrePatch 1.0.0.0]
[Info   :   BepInEx] 2 patcher plugins loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Info   : …
```
> Load the trainer as SptAki/BepInEx module instead of using NLog.

- Features/LootItems.cs
Removed the continue from ShowCorpses check. This broke searching inside corpses for items that are tracked.
> Corpse search fix

- Features/Health.cs
Also enabled ability to toggle Energy/Hydration drain and removal of negative effects. A little bit hackish for the demi-god mode because I couldn't figure out how to bypass damage if the body part being targeted for damage is  chest/head. One side effect of the negative effect toggle is that all the negative effects are removed but you still limp until you take a stim/medicine etc. Credit to S3RAPH's Tarky Menu for the target bone code.
> Prototype Demi-god mode

- Features/BaseMapToggleFeature.cs
- Features/Map.cs
- Features/Radar.cs
When drawing the full screen map we use WorldPointToScreenPoint which incorporates the DLSS scaling, for the minimap we use WorldToScreenPoint and subtract the screen height as for some reason this isn't affected by DLSS???. Reordered some variables to prevent having to add a second function within BaseMapToggleFeature. Also streamlined radarSize instead of sizeX and sizeY as we don't need both for a square.
Added in compass function that rotates with map view, some reason it inherits the enemy colors?
> Map view and Radar map fixes

- Features/Players.cs
Moved the aiming check to a subroutine to prevent erroneously returning when no optic is present on weapon. Fixes #326 and some of #324
> ESP fix for weapons without optics

- Features/Players.cs
Added option to hide NotShootable colors depending on preference. Added per request [#299](https://github.com/sailro/EscapeFromTarkov-Trainer/issues/299#issuecomment-1464114820)
> Added toggle for notshootable

- Features/Map.cs
Fixes #346 
We are already doing this for the `Commands` feature, to not store the GUI state, or `GameState`.
> Do not save map Enabled state.

- Features/BaseMapToggleFeature.cs
- Features/GameState.cs
- Features/Map.cs
- Features/PointOfInterests.cs
This adds POIs to map overview by switching between camera and map camera as needed. Additionally included better check for distance when in map view by assigning the camera y position to match the poi y position.
> Add POIs to map overview

- Features/Commands.cs
- Features/LootItems.cs
- README.md
Removed loadwl command as we have now incorporated it into an option under the Loot feature. If the option is on we assign the Wishlist variable to the wishlist class G2903 or null as appropriate. Then when performing checks in TryAddRecordIfTracked() we shortcut if the item was found in the tracklist or if the Wishlist is null.
Wasn't sure if Wishlist should be private or not. Feel free to change if needed.
Fixes #337
> TrackWishlist in Loot feature

- Features/Quests.cs
No need to do costly FindObjectsOfType<PlaceItemTrigger>() and FindObjectsOfType<ExperienceTrigger>() if we have no started quests
> No need to do costly FindObjectsOfType<>() if we have no started quests

- Extensions/CameraExtensions.cs
- Features/Aimbot.cs
- Features/Bones.cs
- Features/Players.cs
- Features/PointOfInterests.cs
- UI/Render.cs
Players.cs
Refactored scope w2s function to reduce duplicated code and optimize with Vector2 versus Vector3. Moved Head and Left Shoulder visibility checks up to shortcut if we can't see them either in scope or in the world. Added GetScopeParameters() to get various scope parameters to allow access without repeated fetching from the engine. This could be slightly optimized to only update if the isAiming state changes but I don't think it affects much
CameraExtension.cs
Updated IsScreenPointVisible to WorldPointToVisibleScreenPoint and adjusted checks as necessary to use only Vector2 outside of the initial check. Checks are found in Players, Aimbot, and PointOfInterests features.
Bones.cs
Refactored Bones feature to reduce duplicated code and improve readability. Enable only drawing the …
> Refactor and optimize

- Features/Players.cs
> Disable custom occlusion/culling system, making the chams flickering / partially rendering / not rendering at all

- Features/Ammunition.cs
- Features/WallShoot.cs
- Model/ShotWrapper.cs
- NLog.EFT.Trainer.csproj
Previously `wallshoot` feature was horribly slow, because of the use of `FindObjectsOfType` and `GetComponentsInChildren`. This was even causing FPS drops.
We can achieve the same thing by hooking `BallisticCollider.IsPenetrated`, and converting the feature from `CachableFeature<BallisticCollider[]>` to `ToggleFeature`.
Fixes #368
> Rewrite WallShoot feature

- Features/Commands.cs
- NLog.EFT.Trainer.csproj
- README.md
> Add template command

- Features/Feature.cs
- Features/FeatureRenderer.cs
Quite happy with this one.
Previously it was mandatory to open the console while having the Trainer menu opened to be able to change settings in-raid.
Now the trainer menu behaves exactly like the console: when Enabled, the mouse cursor is now displayed without locking. No need to use the console anymore.
> Add cursor support

- Properties/Strings.zh-cn.resx
Fixed autoaim being incorrectly translated as "silent aim" and colloquial descriptions of certain features
> Optimize Chinese translation again，Fixed autoaim being incorrectly translated as "silent aim"

- ConsoleCommands/BaseTemplateCommand.cs
- ConsoleCommands/Spawn.cs
- ConsoleCommands/SpawnBot.cs
- ConsoleCommands/SpawnQuestItems.cs
- NLog.EFT.Trainer.csproj
- Properties/Strings.Designer.cs
- Properties/Strings.fr.resx
- Properties/Strings.resx
- Properties/Strings.zh-cn.resx
- README.md
Spawn items-to-find in active quests.
This will not spawn location-specific / quest-items like folder 033 etc, but all generic items like batteries, injectors, that you can find everywhere.
https://github.com/user-attachments/assets/5c206d89-e57b-4f54-9c85-dbc35ae945f8
> Add `spawnqi` command.

- Features/Examine.cs
- Installer/InstallCommand.cs
- Installer/Installation.cs
- Installer/Installer.csproj
- Installer/VersionChecker.cs
- detect SPT-AKI and display the prompt even before trying to compile (because we will probably fail)
- add `C:\SPT` to the well-known list of installations (SPT-AKI default installation path)
- detect when SPT-AKI was never run, and add another warning given it seems hard to understand :)
> Refine installer

- Installer/Installation.cs
- Installer/Registry.cs
- Installer/VersionChecker.cs
Fixes #565
After running/quitting `SPT.Launcher.exe` or `SPT.Server.exe`:
> Detect SPT-AKI install locations from MUI cache

- ConsoleCommands/Spawn.cs
- KnownTemplateIds.cs
Improve `spawn` command:
- spawn complete armors with proper specs (instead of using hardcoded plates)
- spawn complete weapons 
Examples with `spawn "colt m4a1"`:
> Improve spawn command
