sailro/EscapeFromTarkov-Trainer

Extensions/PlayerExtensions.cs, Features/NightVision.cs, Features/ThermalVision.cs
Night/Thermal : Do not interact if the player is already wearing a compatible equipment
Fixes #225 
Fixes #51
=> Night/Thermal : Do not interact if the player is already wearing a compatible equipment

Features/Ammunition.cs, Model/ShotWrapper.cs, NLog.EFT.Trainer.csproj, README.md
Fixes https://github.com/sailro/EscapeFromTarkov-Trainer/issues/285
=> Prototype for unlimited ammo

Features/Stamina.cs, Features/ToggleFeature.cs
Stores and restores original stamina values prior to modifying them. Added UpdateWhenDisabled method to ToggleFeature. Added AimRangeFinderDrainRate as this was not previously set to 0. Fixes #289
=> Toggle fix for stamina

Features/Players.cs, Features/Radar.cs
@solareon for your review.
I think it's cleaner using an enum to filter content on the radar, instead of using int consts.
And I'm re-using the `GetPlayerColors` we have on `Players`, just needed to change the scope to `public`.
=> Refactor and introduce HostileType enum

Extensions/CameraExtensions.cs, Features/Bones.cs, Features/Players.cs
~~Skeletons are pretty close to where they should be when zoomed in but does not hide lines/boxes that are outside of the scope properly. The function CheckScopeProjection() should do the trick but I'm missing something to make it work correctly.~~
Based upon code from these two sources from [exodus666](https://www.unknowncheats.me/forum/members/1434523.html)
[https://www.unknowncheats.me/forum/3679797-post9051.html](https://www.unknowncheats.me/forum/3679797-post9051.html)
[https://www.unknowncheats.me/forum/3399378-post6940.html](https://www.unknowncheats.me/forum/3399378-post6940.html)
@sailro ~~if you can take a look and see if I'm missing something obvious or I've gone about implementing this the wrong way and I'll do some updates.~~
=> Prototype fix for Wallhack Zoom & Shootable Rewrite

Features/BaseMapToggleFeature.cs, Features/Map.cs, Features/Radar.cs
Quite happy with this refactor.
In the end we have three cases:
- we render on the map camera when in map mode
- we render on the map camera when in radar mode and ShowMap
- we render on the FPSCamera when in radar mode and !ShowMap
We always know if the map camera is active : MapCamera!=null && MapCamera.enabled
Thanks to this we can handle all the cases.
=> OOP Refactor for map fixes

Features/BaseMapToggleFeature.cs, Features/GameState.cs, Features/Hud.cs, Features/Map.cs, Features/Players.cs, Features/PointOfInterests.cs, Features/Radar.cs, NLog.EFT.Trainer.csproj
Just a quick prototype.
Perhaps we'll need to disable all other OnGUI() when toggling the full map.
We can add ZoomIn/ZoomOut using the mouse/keys
We can reuse the teleport code we have in `FreeCamera` to quickly move to a location.
We can add a specific compass (we have one in the HUD -we need to use camera.transform for it as well istead of player.transform-)
=> Extract map logic and add fullscreen map feature

Configuration/ColorConverter.cs
Full explanation in #334 issue
Fixes #334 
Fixes #324
=> Fix Loot colors

Features/BaseMapToggleFeature.cs, Features/Map.cs, Features/Radar.cs, Features/Weather.cs, README.md, UI/Render.cs
Added option to prevent changing time of day to prevent issues with night raids. Added player marker to full map view and replaced smaller crosshair on mini map with player marker.
=> Map QOL Changes

Features/Commands.cs
Re-use the same optimization that we made to `LootItems.RefreshData` to list loot from the command line.
=> Use world.ItemOwners for the `list` command

Features/Ammunition.cs, Features/GameState.cs, Features/Hits.cs, Features/LootableContainers.cs, Features/WallShoot.cs, Model/ShotWrapper.cs, README.md
**master**:
```
Target EscapeFromTarkov (0.13.1.25206) in C:\Battlestate Games\sptarkov.
>> Resolved System to C:\Battlestate Games\sptarkov\EscapeFromTarkov_Data\Managed\System.dll.
>> Resolved System.Core to C:\Battlestate Games\sptarkov\EscapeFromTarkov_Data\Managed\System.Core.dll.
>> Resolved netstandard to C:\Battlestate Games\sptarkov\EscapeFromTarkov_Data\Managed\netstandard.dll.
>> Resolved Assembly-CSharp to C:\Battlestate Games\sptarkov\EscapeFromTarkov_Data\Managed\Assembly-CSharp.dll.
>> Resolved bsg.console.core to C:\Battlestate Games\sptarkov\EscapeFromTarkov_Data\Managed\bsg.console.core.dll.
>> Resolved Comfort to C:\Battlestate Games\sptarkov\EscapeFromTarkov_Data\Managed\Comfort.dll.
>> Resolved Comfort.Unity to C:\Battlestate …
```
=> Fix new object model used in EFT 0.13.1.25206 / spt-aki 3.6.0

Features/Commands.cs
=> Fix window coordinates

Features/Ammunition.cs, Features/Health.cs, Features/Hits.cs, Features/Quests.cs, README.md
=> Add support for EFT 3.7.0.

Installer/CompilationContext.cs, Installer/Compiler.cs, Installer/InstallCommand.cs, Installer/Installation.cs, Installer/Installer.csproj, Installer/UTF8StringWriter.cs
and bump Roslyn to 4.8 to enable C# 12 compilation for the trainer later
=> Move installer code to C# 12

BepInExPlugin/BepInExPlugin.csproj, Configuration/ConfigurationManager.cs, Configuration/OrderedProperty.cs, Extensions/NotNullWhenAttribute.cs, Features/Ammunition.cs, Features/BaseMapToggleFeature.cs, Features/Bones.cs, Features/Commands.cs, Features/ExfiltrationPoints.cs, Features/FeatureFactory.cs, Features/Grenades.cs, Features/Hits.cs, Features/Hud.cs, Features/LootItems.cs, Features/LootableContainers.cs, Features/Players.cs, Features/Quests.cs, Features/SceneDumper.cs, Features/ShaderCache.cs, Features/TrackedItem.cs, Installer/Compiler.cs, Installer/Installer.csproj, Model/ReflectionWrapper.cs, NLog.EFT.Trainer.csproj, UI/EnumPicker.cs
We need to update the installer release before merging this one
=> Move trainer assemblies to C# 12

Features/LootableContainers.cs, KnownTemplateIds.cs
1. Added Airdrop container Id to KnownTemplateId.cs
2. Added airdrop container Id to the container checking logic in LootableContainers.cs
=> Added Airdrop highlight function to the lootable container feature.

Features/LootItems.cs, Features/LootableContainers.cs
=> Move Corpses features from Loot to LootItems (a corpse is a container)

Features/Commands.cs, Features/LootItems.cs, Features/TrackedItem.cs
=> Fix rarity search with match all

Features/CachableFeature.cs, Features/ExfiltrationPoints.cs, Features/LootItems.cs, Features/LootableContainers.cs, Features/PointOfInterests.cs, Features/Quests.cs
=> Use object pooling for all PointOfInterests instead of allocating all objects for every refresh

Installer/InstallCommand.cs, Installer/Installer.csproj
=> Fix installer outline copy

Features/Commands.cs, NLog.EFT.Trainer.csproj, README.md
Fixes #477 
Demo video
https://www.dropbox.com/scl/fi/h5tcxhehys48c6v322skk/tarkov.spawn.command.mp4?rlkey=wi037fm11unokyj3o0kpdaews&dl=0
=> Add spawn command

Installer/CompilationContext.cs, Installer/InstallCommand.cs
=> Update installer wording when SSL issues are found.

Features/Health.cs
So we cannot die from special stims anymore
Fixes #516
=> Improve Health hooking.

NLog.EFT.Trainer.csproj, Properties/Strings.zh-cn.resx
=> Add localized Chinese translations

Properties/Strings.zh-cn.resx
I found that the Chinese translation seemed to have some problems, causing some functions to look awkward. I have fixed these problems
=> Optimize Chinese translation again

ConsoleCommands/SpawnBot.cs
Possible fix for https://github.com/sailro/EscapeFromTarkov-Trainer/issues/555. Not sure if this is the most optimal location
=> fix(commands/spawnbot): edge case for multiple matches

Properties/Strings.Designer.cs, Properties/Strings.fr.resx, Properties/Strings.resx, Properties/Strings.zh-cn.resx, README.md
Nothing to change regarding configuration nor code, we are already using `EFT.Trainer.Features.Players` in the `trainer.ini` file.
=> Reword/consistency, do not use `wallhack` term anymore.

Features/NoFlash.cs, NLog.EFT.Trainer.csproj, Properties/Strings.Designer.cs, Properties/Strings.fr.resx, Properties/Strings.resx, Properties/Strings.zh-cn.resx, README.md
No persistent flash or eye-burn effect after a flash grenade.
=> Add noflash feature

ConsoleCommands/BaseTemplateCommand.cs, ConsoleCommands/Spawn.cs, ConsoleCommands/Template.cs, Features/AirDrop.cs, Features/TemplateHelper.cs, KnownTemplateIds.cs, NLog.EFT.Trainer.csproj, Properties/Strings.Designer.cs, Properties/Strings.fr.resx, Properties/Strings.resx, Properties/Strings.zh-cn.resx, README.md
=> Triggers an airdrop at the player's location

Installer/Installer.csproj
Should fix #666 
See https://github.com/dotnet/runtime/issues/108589
=> Disable CET

Properties/Strings.jp.resx
=> Optimize Japanes translation
